"""Add utm fields to gift model

Revision ID: 48595ddaca3c
Revises: 5e7c9827cf92
Create Date: 2025-06-22 13:54:54.303730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48595ddaca3c'
down_revision: Union[str, Sequence[str], None] = '5e7c9827cf92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utm_campaign', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('utm_content', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('utm_term', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.drop_column('utm_term')
        batch_op.drop_column('utm_content')
        batch_op.drop_column('utm_campaign')

    # ### end Alembic commands ###
