"""Add popup content fields to Gift model

Revision ID: 51d434079ea4
Revises: 07f547db094d
Create Date: 2025-06-21 20:16:48.041606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d434079ea4'
down_revision: Union[str, Sequence[str], None] = '07f547db094d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('popup_image_url', sa.String(), nullable=True))
    op.add_column('gifts', sa.Column('popup_description', sa.Text(), nullable=True))
    op.alter_column('gifts', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gifts', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('gifts', 'popup_description')
    op.drop_column('gifts', 'popup_image_url')
    # ### end Alembic commands ###
