"""Replace popup fields with popup_config JSON

Revision ID: 5e7c9827cf92
Revises: 640083c3ce29
Create Date: 2025-06-21 20:34:23.598396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7c9827cf92'
down_revision: Union[str, Sequence[str], None] = '640083c3ce29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popup_config', sa.JSON(), nullable=True))
        batch_op.drop_column('popup_description')
        batch_op.drop_column('popup_image_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popup_image_url', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('popup_description', sa.TEXT(), nullable=True))
        batch_op.drop_column('popup_config')

    # ### end Alembic commands ###
