"""Add utm_config to Gift model

Revision ID: 7719fd73cfaf
Revises: 48595ddaca3c
Create Date: 2025-06-22 15:38:16.314931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7719fd73cfaf'
down_revision: Union[str, Sequence[str], None] = '48595ddaca3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utm_config', sa.JSON(), nullable=True))
        batch_op.drop_column('utm_campaign')
        batch_op.drop_column('utm_content')
        batch_op.drop_column('utm_term')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utm_term', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('utm_content', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('utm_campaign', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('utm_config')

    # ### end Alembic commands ###
